### ISSUE TITLE
Pagelist with links to next pages for quick navigation not working anymore in Plone 4.3.3

### ISSUE THREAD

**Issue by pabo3000** [plone/plone.app.querystring#24] opened 2014-04-23 09:10 UTC
Steps to reproduce:
* Fresh install Plone 4.3.3
* Enter folder "News" and create perhaps 10 news items and publish them
* Limit the search results of the collection to "4"
* Visit News
* You will see that there is only [1]. The links to next pages are missing.

Steps to cure:
* pin version: plone.app.querystring: 1.0.8

It seems that plone.app.querystring 1.1.1 is buggy.

**Comment by jensens** [comment] 2015-04-27 23:11
is this still valid with latest releases for plone 4.3.x and plone 5?

**Comment by mauritsvanrees** [comment] 2015-10-29 23:41
In version 1.2.1 I see this in the changelog:

```
- Fix querybuilder code if results object does not provide an
  actual_results_count attribute. This regression has been introduced in
  release 1.1.1 (fixed broken handling of limit and batch size).
  [timo]
```

That seems to have fixed it. I cannot reproduce this on a fresh Plone 4.3.7 (well, coredev) site.

I will close this issue. Please reopen if you still see this problem.

**Closed by mauritsvanrees** 2015-10-29 23:41 UTC

**Comment by pabo3000** [comment] 2015-10-30 11:43
confirm, that it works in 4.3.7 and 5
