### ISSUE TITLE
CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.querystring#37] opened 2015-05-08 16:41 UTC
The field 'Sort on'  in collection, list index of type 'ZCTextIndex' if the record is placed as 'sortable'. When you create a filter and an index 'ZCTextIndex' is selected in 'Sort on', the error below occurs  in the return of the ajax call (querybuilder_html_results):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.app.querystring.querybuilder, line 58, in html_results
    Module plone.app.querystring.querybuilder, line 49, in __call__
    Module plone.app.querystring.querybuilder, line 116, in _makequery
    Module Products.CMFPlone.CatalogTool, line 393, in searchResults
    Module Products.ZCatalog.ZCatalog, line 604, in searchResults 
    Module Products.ZCatalog.Catalog, line 916, in searchResults
    Module Products.ZCatalog.Catalog, line 894, in _getSortIndex

    CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

The field 'Sort on' should not list index of type 'ZCTextIndex'.

**Comment by hvelarde** [comment] 2015-05-08 19:53
@idgserpro I think we have 2 different issues here: one regarding the index type and displaying it as sortable, which belongs to this package, and another relative to the other package, collective.nitf, and the type of index selected for that specific field.

**Comment by idgserpro** [comment] 2015-05-08 20:39
@hvelarde I agree that the collective.nitf should be fix. The indexes that are ZCTextIndex should be

```xml
<value key="sortable">False</value>
```

[here](https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/profiles/default/registry.xml).

**Comment by hvelarde** [comment] 2015-05-11 12:20
so this is invalid here as the problem is there.

**Comment by idgserpro** [comment] 2015-05-11 12:42
I do not think this is invalid. The field 'Sort on' should not list index of type 'ZCTextIndex'. Other products may make the same mistake of collective.nitf. plone.app.querystring should not allow it.

**Comment by hvelarde** [comment] 2015-05-11 14:23
I don't know then and someone else should review it.

**Comment by winstonf88** [comment] 2015-09-01 14:25
I agree with @idgserpro. plone.app.querystring is where it should be fixed. 
If this type of index can not be used for sorting it should not be an option for the user.

**Closed** 2015-09-18 13:56 UTC
